### ISSUE TITLE
Add more stats

### ISSUE THREAD

**Issue by syymza** [Financial-Times/email-manual-editor#139]
These are the stats we **should** collect:
![image](https://cloud.githubusercontent.com/assets/419147/10372703/176a6326-6de1-11e5-8fbe-7c08d43d3859.png)

**Comment by josephcera** [comment]
Bounces: "Total boucnes", “hard bounce count” and “soft bounce count” breakout would be ideal

**Comment by syymza** [comment]
Currently added:

- Total sent
- Total delivered
- Total open
- Total clicks
- Total bounces

**Comment by syymza** [comment]
closed by #140
