### ISSUE TITLE
Add some text/a notice when an email list is empty

### ISSUE THREAD

**Issue by syymza** [Financial-Times/email-manual-editor#185]
Currently we do not provide any feedback to the users if he filers the emails and the result is empty.

<img width="922" alt="screen shot 2015-11-04 at 12 36 25" src="https://cloud.githubusercontent.com/assets/419147/10938279/bea8c78a-82f0-11e5-9a41-53078f874c27.png">

We **could** improve it.

**Comment by venil7** [comment]
closed by #195
