### ISSUE TITLE
Dashboard showing stats per email for ops / customer services

### ISSUE THREAD

**Issue by geek-caroline** [Financial-Times/email-manual-editor#201]
With the release of a large email we need to start considering the needs of ops / customer service who will get large numbers of customers contacting them if an email fails to send.

To this end, they need an easy way to see the delivery rates for the past few days (I'd suggest 15 or 16 days to encompass two weekend send rates) on all email products that are going through our platform (i.e. Next daily digest, weekly digest and MBA newslines email) allowing them to identify whether there has been a general issue for a product  so they can easily establish whether an individual customer's complaint is unique to that customer or likely to be a wider problem.

They currently use the daily reports emailed to them from eBay for this purpose.

This dashboard will also enable them to have a view on which emails have been migrated into the new email platform.

(This dashboard will probably also be useful for our daily sanity checking to ensure no 'unexpected' send drops)

**Comment by syymza** [comment]
closed by #221
