### ISSUE TITLE
Create an author-widget component

### ISSUE THREAD

**Issue by syymza** [Financial-Times/email-manual-editor#21]
We need a component that allows represent the email author in some of the *templates*.

The widget contains a default author profile image and name, plus a date.

![screen shot 2015-08-27 at 16 02 20](https://cloud.githubusercontent.com/assets/419147/9524118/183fdfb0-4cd5-11e5-946d-f0956bfc4e85.png)

Templates will contain a {{authorWidget}} placeholder for it

**Comment by venil7** [comment]
closed by https://github.com/Financial-Times/email-manual-editor/pull/33
