### ISSUE TITLE
Email status

### ISSUE THREAD

**Issue by syymza** [Financial-Times/email-manual-editor#22]
We **must** indicate if an email has been already sent.
We **must** indicate if an email is ready to be sub-edited.
We **must** indicate if an email has been sub-edited.

**Comment by syymza** [comment]
Identified mail flags:

  - `dirty`
  - `valid`
  - `sent`
  - `toSubEdit`
  - `subEdited`
  
All these flags are Boolean and their default value is `false`.
Each mail also contains an optional field `sendTime`, of type `Date`.

**Comment by venil7** [comment]
fixed by #47
