### ISSUE TITLE
Delete anchor link type from link dialog

### ISSUE THREAD

**Issue by syymza** [Financial-Times/email-manual-editor#231]
The anchor link type in the link dialog is not usable in our setup. It **could** be removed.

**Comment by syymza** [comment]
<img width="635" alt="screen shot 2015-11-23 at 17 02 12" src="https://cloud.githubusercontent.com/assets/419147/11343441/fcc4c22c-9203-11e5-96fb-7c4b82647a0e.png">

**Comment by venil7** [comment]
closed by #232
