### ISSUE TITLE
Pagination should not be preserved when changing the 'Display' filter

### ISSUE THREAD

**Issue by syymza** [Financial-Times/email-manual-editor#263]
Currently, if you are in a page > 1 and you edit the selection on the display filter you end up in a broken state:

<img width="1263" alt="screen shot 2016-01-07 at 11 47 48" src="https://cloud.githubusercontent.com/assets/419147/12169948/803548e0-b534-11e5-9ea7-a97ee6c23e00.png">

It is a **bug** and it **should** be fixed.

**Comment by venil7** [comment]
fixed by #266
