### ISSUE TITLE
Pagination appears in state of previous template when switching to a new template

### ISSUE THREAD

**Issue by mowlds** [Financial-Times/email-manual-editor#265]
1. Select 'Energy Source' template filter from email list - Observe that no pagination is displayed as there is only 1 page of emails 
![energy source normal](https://cloud.githubusercontent.com/assets/16611163/12201521/d3c52ec4-b61c-11e5-8b8f-11889df151ab.png)

2. switch to 'All' Template filter
3. Navigate to page 2 of 'All'
4. Switch to 'Energy source' template or any template with only 1 page of emails
5. Page is broken
![energy source broken](https://cloud.githubusercontent.com/assets/16611163/12201563/feaf80d0-b61c-11e5-9349-d4fd1e4fa103.png)

expected result:
5. 'Energy source' template should be shown with emails without any pagination as per step 1

similar to issue #263

**Comment by venil7** [comment]
fixed by #266, in staging

**Comment by syymza** [comment]
This is actually still a bug

**Comment by venil7** [comment]
unable to replicate

**Comment by venil7** [comment]
fixed again :smile_cat: by #312
