### ISSUE TITLE
URL for default Authors to link to default author pages

### ISSUE THREAD

**Issue by mowlds** [Financial-Times/email-manual-editor#271]
Clicking on the link for a default author currently does not take you to the corresponding page for that author, instead it goes to a corresponding topic page ie. 

1. Compose new email for energy source template
2. Select any default Author
3. Click on the Authors name on the email preview pane
4. User is directed to topic page relating to the template (Energy)

At step 4 i would expect the user to be directed to the authors 'topic' page

**Comment by venil7** [comment]
@mowlds, this is desired behaviour
