### ISSUE TITLE
'Sending Date' can be set to the past

### ISSUE THREAD

**Issue by mowlds** [Financial-Times/email-manual-editor#272]
![sendingdatepast](https://cloud.githubusercontent.com/assets/16611163/12357367/6025a218-bb9f-11e5-94df-e1f4f7a211ed.png)

Unless there is a reason to be able to do this that I am not aware of the user should not be able to set a sending date in the past, Is it possible to have the date that is shown on the email to be the current date or the scheduled sending date?

**Comment by venil7** [comment]
fixed by #277
