### ISSUE TITLE
Improve validation feedback for urls

### ISSUE THREAD

**Issue by syymza** [Financial-Times/email-manual-editor#30]
The validation for URLs in the footer-widget component **could** be improved. No feedback is shown at the moment if an invalid email is inserted. This is especially problematic if the user doesn't paste the http/https sub-strings:

<img width="614" alt="screen shot 2015-09-01 at 15 22 08" src="https://cloud.githubusercontent.com/assets/419147/9606767/4a1cf7fc-50bd-11e5-884d-252defcbd212.png">

**Comment by venil7** [comment]
fixed by #103
