### ISSUE TITLE
per template permissions toggle only shows as amber when all templates are selected

### ISSUE THREAD

**Issue by mowlds** [Financial-Times/email-manual-editor#310]
**Steps**
1. Select Users tab from the menu
2. Select any user from the list
3. Click the 'select templates' button for any option under 'per template permissions' (eg. Delete emails)
4. Select 'All' from the list and click OK
5. Observe that on the user screen, the toggle is only switched to amber

**Expected Result**
5. Toggle should be green when all templates are selected

**Comment by mowlds** [comment]
**Steps**
1. Select Users tab from the menu
2. Select any user from the list
3. Click the 'select templates' button for any option under 'per template permissions' (eg. Delete emails)
4. Select 'All' from the list and click OK
5. Observe that on the user screen, the toggle is only switched to amber

**Expected Result**
5. Toggle should be green when all templates are selected

**Comment by venil7** [comment]
Hi Michael,

this is `as designed` behaviour, by selecting all boxes in custom dialog - you are giving permission to all current templates, but not any future ones - hence amber, to give access to all (including future ones) flip the switch outside custom dialog

Art
