### ISSUE TITLE
Make better use of the space on more permissions screen when window is smaller sized

### ISSUE THREAD

**Issue by mowlds** [Financial-Times/email-manual-editor#313]
On attached screenshot, browser window is made smaller to fit half the size of the screen

![screen shot 2016-02-12 at 16 29 49](https://cloud.githubusercontent.com/assets/16611163/13013360/12096970-d1a7-11e5-86da-7a2f22cdd7c6.png)

or perhaps the overlay could be made slightly bigger to fit more content

**Comment by venil7** [comment]
@mowlds what resolution/browser are you testing this in?
I cant seem to replicate it unless I shrink browser significantly,

As internal product we didnt have requirement to make it responsive, or support really narrow screens

I will close this issue, but if you think you can replicate it in regular environment, please feel free to reopen.
