### ISSUE TITLE
Incorrect time format on markets data widget on email

### ISSUE THREAD

**Issue by mowlds** [Financial-Times/email-manual-editor#325]
On the editor tool, after selecting refresh to add the widget, the time is shown in a 12hr AM/PM format (ie. Last updated: Today at 2:03 PM) however on the email itself the time is in 24 hour format (0203 GMT) which is incorrect.

![marketsgmt](https://cloud.githubusercontent.com/assets/16611163/13178127/36340378-d715-11e5-9b0b-a287192353ef.png)

**Comment by venil7** [comment]
fixed by #326
