### ISSUE TITLE
Add new params for urls to ex CRM 

### ISSUE THREAD

**Issue by syymza** [Financial-Times/email-manual-editor#356]
We have received a list of params to add to CRM emails. That'll change the model for params to a proper object.

**Comment by syymza** [comment]
Best of Lex: ftcamp=engage/email/pwe/newsmine/new/crm&utm_source=newsmine&utm_medium=email&utm_term=pwe&utm_campaign=new

Editor's Choice:
ftcamp=engage/email/new/editors_choice/pwe/crm&utm_source=editors_choice&utm_medium=email&utm_term=new&utm_campaign=pwe

Newsmine:
ftcamp=engage/email/pwe/newsmine/new/crm&utm_source=newsmine&utm_medium=email&utm_term=pwe&utm_campaign=new

**Comment by venil7** [comment]
@Mus and @MartinFallon to discuss feasibility of this (as discussed)

**Comment by MartinFallon** [comment]
@venil7 I think you are referring to the wrong Martin here.
