### ISSUE TITLE
FT Weekend template appears with all images alongside each other on some clients

### ISSUE THREAD

**Issue by mowlds** [Financial-Times/email-manual-editor#362]
The weekend template should appear as 2 columns on desktop clients but on some clients it is showing with all images alongside each other in multiple columns.

On Outlook each image appears in it's own column as per the screenshot but fits on one page
![ftweekendoutlook](https://cloud.githubusercontent.com/assets/16611163/14023165/09dc40a2-f1db-11e5-83bb-9992a1f01c7c.PNG)

on another client, AOL mail on firefox, the images bleed out of the template
![aolmailftweekend](https://cloud.githubusercontent.com/assets/16611163/14023225/56a711fa-f1db-11e5-9698-d118fdab8230.PNG)

**Comment by syymza** [comment]
@mowlds is this still the case?

**Comment by venil7** [comment]
fixed by #372
