### ISSUE TITLE
Some small visual defects on emails viewed on outlook

### ISSUE THREAD

**Issue by mowlds** [Financial-Times/email-manual-editor#363]
you can see on the outlook 2010 client that there is a blank white space which appears under any orange header
![ftweekendoutlook](https://cloud.githubusercontent.com/assets/16611163/14023385/06d6428a-f1dc-11e5-8b83-a8f0a1bd56ba.PNG)

And also on the outlook 2013 client the author name and the subscribe to ft button do not appears correctly
![ftweekendoutlook2013](https://cloud.githubusercontent.com/assets/16611163/14023531/a9550276-f1dc-11e5-9c70-29165b3e322b.PNG)

**Comment by venil7** [comment]
@mowlds interesting one,
we tested it in Litmus previously and it showed up ok
how did you test?

**Comment by mowlds** [comment]
@venil7 I had used litmus also. I'm aware that sometimes litmus doesn't always render the email properly but I tried on several occasions and it came up like this every time.

Now I have litmus working properly I am going to try it on each template that we have

**Comment by venil7** [comment]
fixed by #372
