### ISSUE TITLE
Standard user is unable to select standard newsletters/subscriptions on new nbe page

### ISSUE THREAD

**Issue by mowlds** [Financial-Times/email-manual-editor#366]
when signed in as a standard user (mobilestandard@ftqa.org) you are unable to select the standard newsletters or briefings in the new  nbe.ft.com site (http://www.ft.com/thirdpartywrapper/emealertshub?ft_site=falcon&desktop=true)

There is 'commodities note;' under standard subscription briefings and 'opening quote' under hand curated newsletters which should be available for a standard user to select

![standarduser](https://cloud.githubusercontent.com/assets/16611163/14147591/04a88db2-f694-11e5-9c8e-183d9290b6d5.PNG)

**Comment by syymza** [comment]
Fixed
