### ISSUE TITLE
unsubscribe button remains checked after selecting other briefings on new nbe page

### ISSUE THREAD

**Issue by mowlds** [Financial-Times/email-manual-editor#367]
1. go to http://www.ft.com/thirdpartywrapper/emealertshub?ft_site=falcon&desktop=true
2. select any items to subscribe to
3. scroll to the bottom and select unsubscribe, observe that the selected options are deselected
4. while unsubscribe is selected, select any of the items to subscribe to
5. observe that the unsubscribe button is still checked

on the current nbe.ft.com page, the unsubscribe button is deselected following the steps on step 5

![unsubscribenbe](https://cloud.githubusercontent.com/assets/16611163/14172224/ea5773f6-f72e-11e5-930d-fe1d7465292a.png)

**Comment by syymza** [comment]
I put a button to replace the checkbox
