### ISSUE TITLE
Add permissions flags

### ISSUE THREAD

**Issue by syymza** [Financial-Times/email-manual-editor#40]
Users **could** have different permission levels.

A possible hierarchy, is: 

 - `subEditor`: can only edit emails with the `toSubEdit` flag
 - `editor`: `subEditor` permission + can add new emails
 - `admin`: `editor` permissions, + can add users

**Comment by syymza** [comment]
This issue depends on #39

**Comment by syymza** [comment]
The requirements for this issue have changed. We are going to have a list of boolean permission for the users (e.g. `canSend`)

**Comment by venil7** [comment]
fixed in #267
