### ISSUE TITLE
Redirect to https

### ISSUE THREAD

**Issue by syymza** [Financial-Times/email-manual-editor#86]
The http endpoint is not whitelisted in the Google console. We **could** to redirect the user accessing the app over HTTP to the HTTPS endpoint.

Possible approach:
http://stackoverflow.com/questions/7185074/heroku-nodejs-http-to-https-ssl-forced-redirect

**Comment by syymza** [comment]
Also worth considering: https://github.com/florianheinemann/express-sslify

**Comment by venil7** [comment]
closed by #88
